//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeBank.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orden
    {
        public int idOrden { get; set; }
        public int idOferta { get; set; }
        public Nullable<int> idUser { get; set; }
        public int idEstado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Ofertas Ofertas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
