//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeBank.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenOfertas
    {
        public int idOferta { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Titulo { get; set; }
        public double Tiempo { get; set; }
        public int OfertaUser { get; set; }
        public int OrdenUser { get; set; }
        public int idEstado { get; set; }
    }
}
