//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeBank.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResumenActividad
    {
        public string NombreCat { get; set; }
        public string Titulo { get; set; }
        public double Tiempo { get; set; }
        public string NombreEstado { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public System.DateTime fecha_ofer { get; set; }
        public int oferUser { get; set; }
        public Nullable<int> ordenUser { get; set; }
    }
}
