//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeBank.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int idWallet { get; set; }
        public double Balance { get; set; }
        public System.DateTime fecha { get; set; }
        public int idCliente { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
